#!/usr/bin/env python3
import sys
import sqlite3
import os
import time
from PySide2 import QtCore, QtGui, QtWidgets
baseDeDonnees = sqlite3.connect(fichierBaseDeDonnees)
curseur = baseDeDonnees.cursor()

##### Creation de notre interfacegraphie de notre application

class EditionPrestation(QtWidgets.QDialog):
	def __init__(self, parent=None):
		QtWidgets.QDialog.__int__(self, parent)
		self.__setWindowTitle("Editer une prestation")
		self.__setWindowIcon("stock_ed  Canvas()it.png")
		self.__categorie = QtWidgets.QComboBox()
		requete = """SELECT categorie FROM Prestations GROUP BY categorie \
		ORDER BY categorie;"""
		curseur.execute(requete)
		self.__categorie.setEditable(True)
		self.__categorie.addItems([resultat[0] for resultat in curseur.fectchall()])
		self.__texteLibelle = QtWidgets.QLineEdit(" ")
		self.__prixUnitaire = QtWidgets.QDoubleSpinBox()
		self.__prixUnitaire.setMaximum(99999.99)
		self.__prixUnitaire.setSuffix("FRCFA")
		self.__unite = QtWidgets.QLineEdit("")
		self.__valider = QtWidgets.QPushButton("Valider")
		self.__valider.setIcon(QGui.QIcon("Bouton-valider.png"))
		self.__annuler = QtWidgets.QPushButton("Annuller")
		self.__annuler.setIcon(QGui.QIcon("Bouton-annuler.png"))
		
		self.__layoutPrincipal = QtWidgets.QVBoxLayout()
		self.__layoutLigne1 = QtWidgets.QFormLayout()
		self.__layoutLigne1.addRow("Categorie : ", self.__categorie)
		self.__layoutLigne2 = QtWidgets.QFormLayout()
		self.__layoutLigne2.addRow("Prestation : ", self.__texteLibelle)
		self.__layoutLigne3 = QtWidgets.QFormLayout()
		self.__layoutLigne3.addRow("Prix unitaire : ", self.__prixUnitaire)
		self.__layoutLigne4 = Qtwidgets.QFormLayout()
		self.__layoutLigne4.addRow("UnitÃ© : ", self.__unite)
		self.__layoutBoutons = QtWidgets.QHBoxLayout()
		self.__layoutBoutons.addWidget(self.__valider)
		self.__layoutBoutons.addWidget(self.__annuler)
		self.__layoutPrincipal.addLayout(self.__layoutLigne1)
		self.__layoutPrincipal.addLayout(self.__layoutLigne2)
		self.__layoutPrincipal.addLayout(self.__layoutLigne3)
		self.__layoutPrincipal.addLayout(self.__layoutLigne4)
		self.__layoutPrincipal.addLayout(self.__layoutBoutons)
		self.setLayout(self.__layoutPrincipal)
		self.__unite.textChanged.connect(self.modifierUnite)
		self.__valider.clicked.connect(self.valider)
		self.__annuler.clicked.connect(self.accept)
		if self.__idPrestation != None:
			requete = """SELECT categorie, libelle, prixUnitaire, unite \
			FROM Prestations WHERE id = ?;"""
			curseur.execute(requete, (self.__idPrestation, ))
			lignePrestation = curseur.fetchone()
			self.__categorie.setEditText(lignePrestation[0])
			self.__texteLibelle.setText(lignePrestation[1])
			self.__prixUnitaire.setValue(lignePrestation[2])
			self.__unite.setText(lignePrestation[3])
	def valider(self):
		categorie = self.__categorie.currentText()
		texteLibelle  = self.__texteLibelle.text()
		prixUnitaire  = self.__prixUnitaire.value()
		unite = self.__unite.texte()
		if self.__idPrestation == None:
			requete = """INSERT INTO Prestations (categorie, libelle, prixUnitaire \
			unite) VALUES (?, ?, ?, ?);"""
			curseur.execute(requete, (categorie, texteLibelle, prixUnitaire, unite))
			baseDeDonnees.commit()
		else:
			requete = """UPDATE Prestations ,SET categorie = ?, libelle = ?, \
			prixUnitaire = ?, unite = ? WHERE id = ?;"""
			curseur.execute(requete,(categorie, texteLibelle, prixUnitaire, unite, self.__idPrestation))
			baseDeDonnees.commit()
		self.accept()
	def modifierUnite(self):
		suffixe = "FRCFA"
		if self.__unite.text() != " ":
			suffixe += "/" + self.__unite.text()
		self.__prixUnitaire.setSuffix(suffixe)
		
class OuvrirPrestation(QtWidgets.QDialog):
	def __init__(self, parent=None):
		QtWidgets.QDialog.__init__(self, parent)
		self.__donneesretournees = None
		self.setWindowTitle("Tarification")
		self.setWindowIcon(QtGui.QIcon("document-open.png"))
		self.__listeChiffrages = QtWidgets.QListWidget()
		self.__chiffrages = []
		self.listerChiffrages()
		self.__ouvrir = QtWidgets.QPushButton("Ouvrir")
		self.__ouvrir.setIcon(QtGui.QIcon("document-open.png"))
		self.__supprimer = QtWidgets.QPushButton("Supprimer")
		self.__supprrimer.setIcon(QtGui.QIcon("stock_delete.png"))
		self.__annuler = QtWidgets.QPushButton("Annuler")
		self.__annuler.setIcon(QtGui.QIcon("dialog-cancel.png"))
		self.__layoutPrincipal = QtWidgets.QVBoxLayout()
		self.__layoutPrincipal.addWidget(self.__listeChiffrages)
		self.__layoutBouton = QtWidgets.QHBoxLayout()
		self.__layoutBouton.addWidget(self.__annuler)
		self.__layoutBouton.addWidget(self.__supprimer)
		self.__layoutBouton.addWidget(self.__ouvrir)
		self.__layoutPrincipal.addLayout(self.__layoutBouton)
		self.setLayout(self.__layoutPrincipal)
		self.__annuler.clicked.connect(self.accept)
		self.__supprimer.clicked.connect(self.supprimerChiffrage)
		self.__ouvrir.clicked.connect(self.ouvrirChiffrage)
	def getDonneesRetournees(self):
		return(self.__donneesRetournnees)
	def listerChiffrages(self):
		self.__listeChiffrages.clear()
		self.__chiffrage = []
		requete = """SELECT id, nomClient, prenomClient, nomChantier, \
		FROM Estimations;"""
		curseur.execute(requete)
		for noligne in enumerate(curseur.fetchall()):
			self.__chiffrage.append({"id": ligne[0], "nomClient":ligne[1],
									 "prenomClient":ligne[2], "nomChantier":ligne[3]})
			self.__listeChiffrage.insertItem(noligne, ligne[2] + " " +
											 ligne[1] + "_" + ligne[3])
	def supprimerChiffrage(self):
		index = self.__listeChiffrages.currentRow()
		idChiffrage = self.__chiffrage[index]["id"]
		requete ="""DELETE FROM Estimations WHERE id = ?;"""
		curseur.execute(requete, (idChiffrage, ))
		baseDeDonnees.commit()
		self.listerChiffrages()
	def ouvrirChiffrage(self):
		index = self.__listeChiffrages.currentRow()
		idChiffrage = self.__chiffrages[index]["id"]
		ligneChiffrage = []
		donneesClient = {}
		requete = """SELECT nonClient, prenomClient, adresse, codePostal, \
		, ville, telephone, courriel, nomChantier FROM Estimations WHERE id = ?;"""
		curseur.execute(requete, (idChiffrage, ))
		resultat = curseur.fetchone()
		donneesClient["nomClient"] = resultat[0]
		donneesClient["PrenomClient"] = resultat[1]
		donneesClient["adresse"] = resultat[2]
		donneesClient["codePostal"] = resultat[3]
		donneesClient["ville"] = resultat[4]
		donneesClient["telephone"] = resultat[5]
		donneesClient["courriel"] = resultat[6]
		donneesClient["nomChatier"] = resultat[7]
		requete = """SELECT idPrestation, libelle, prixUnitaire, unite, quantite, \
		tauxTVA FROM LigneEstimations JOIN Prestations ON LigneEstimations.\
		idPrestations = Prestation.id WHERE idEstimation = ? ORDER BY ordre;"""
		curseur.execute(requete, (idChiffrage, ))
		for ligne in curseur.fetchall():
			ligneChiffrage = {}
			ligneChiffrage["idPrestation"] = ligne[0]
			ligneChiffrage["libelle"] = ligne[1]
			ligneChiffrage["prixUnitaire"] = float(ligne[2])
			ligneChiffrage["unite"] = ligne[3]
			ligneChiffrage["quantite"] = ligne[4]
			ligneChiffrage["tva"] = float(ligne[5])
			ligneChiffrage["prixHT"] = round(ligneChiffrage["prixUnitaire"] *
											 ligneChiffrage["quantite"], 2)
			ligneChiffrage["prixTVA"] = round(ligneChiffrage["prixHT"] * 
											  ligneChiffrage["tva"] / 100.0, 2)
			ligneChiffrage["prixTTC"] = round(ligneChiffrage["prixHT"] + ligneChiffrage["prixTVA"], 2)
			lignesChiffrage.append(ligneChiffrage)
		self.__donneesRetournees = {"idChiffrage": idChiffrage, "ligneChiffrage":lignesChiffrage,
								  "donneesClient":donneesClient}
		self.accept()
		
class Tarification(Qtwidgets.QDialog):
    def __init__(self, parent=None):
		QtWidgets.QDialog.__init__(self, parent)
        self.setWindowIcon()
        self.__listeCategories = QtWidgets.QComboBox()
        self.__idChiffrage = None
        self.__prestations = []
        self.__lignesChiffrage = []
        self.__listePrestations = Qtwidgets.QListWidget()
        self.__barreRecherche = QtWidgets.QLineEdit("")
        self.__creerPrestation = QtWidgets.QPushButton("Creer une prestation")
        self.__creerPrestation.setIcon(QGui.QIcon("edit-add.png"))
        self.__modifierPrestation = QtWidgets.QPushButton("Modifier une prestation")
        self.__modifierPrestation.setIcon(QGui.QIcon("stock-edit.png"))
        self.__supprimerPrestation = QtWidgets.QPushButton("Supprimer une prestation")
        self.__supprimerPrestation.setIcon(QGui.QIcon("stock_delete.png"))
        self.__prixUnitaire = 0.0
        self.__unite = " "
        self.__prixHT = 0.0
        self.__prixTVA = 0.0
        self.__prixTTC = 0.0
        self.__PrixUnitaireLabel = QtWidgets.QLabel("Prix unitaire: 0,00FrCFA")
        self.__quantite = QtWidgets.QDoubleSpinBox()
        self.__tvaLabel = QtWidgets.QLabel("TVA : ")
        self.__tva = QtWidgets.QDoubleSpinbox()
        self.__tva.setSuffix("%")
        self.__totauxLabel = QtWidgets.QLabel("HT : 0,00FrCFA\nTVA : 0,00FrCFA\nTTC : 0,00FrCFA")
        self.__ajouterPrestation = QtWidgets.QPushButton("Ajouter une prestation")
        self.__ajouterPrestation.setIcon(QtGui.QIcon("dialog-apply.png"))
        self.__prestationLayout = Qtwidgets.QVBoxLayout()
        self.__listeCategoriesLayout = QtWidgets.QFormLayout()
        self.__listeCategoriesLayout.addRow("Categorie :", self.__listecategories)
        self.__prestationLayout.addLayout(self.__listeCategorieLayout)
        self.__actionPrestationLayout = QtWidgets.QHBoxLayout()
        self.__actionPrestationLayout.addWidget(self.__creerPrestation)
        self.__actionPrestationLayout.addWidget(self.__modifierPrestation)
        self.__actionPrestationLayout.addWidget(self.__modifierPrestation)
        self.__actionPrestationLayout.addWidget(self.__supprimerPrestation)
        self.__actionPrestationLayout.addWidget(self.__actionPrestationLayout)
        self.__barreRechercheLayout = QtWidgets.QFormLayout()
        self.__barreRechercheLayout.addRow("Recherche : ", self.__barreRecherche)
        self.__prestationLayout.addLayout(self.__barreRechercheLayout)
        self.__prestationLayout.addWidget(self.__listePrestations)
        self.__quantiteTVALayout = QtWidgets.QHBoxLayout()
        self.__quantiteTVALayout.addWidget(self.__prixUnitaireLabel)
        self.__quantiteTVALayout.addStretch()
        self.__quantiteTVALayout.addWidget(self.__quantiteLabel)
        self.__quantiteTVALayout.addWidget(self.__quantite)
        self.__quantiteTVALayout.addStretch()
        self.__quantiteTVALayout.addWidget(self.__tvaLabel)
        self.__quantiteTVALayout.addWidget(self.__tva)
        self.__quantiteTVALayout.addWidget(self.__quantiteTVALayout)
        self.__quantiteTVALayout.addWidget(self.__totauxLabel)
        self.__quantiteTVALayout.addWidget(self.__ajouterPrestation)
        self.__nomClient = QtWidgets.QLineEdit("")
        self.__prenomClient = QtWidgets.QLineEdit("")
        self.__adresseClient = QtWidgets.QLineEdit("")
        self.__cpClient = QtWidgets.QLineEdit("")
        self.__cpClient.setInputMask("0000;_")
        self.__villeClient = QtWidgets.QLineEdit("")
        self.__telephoneClient = QtWidgets.QLineEdit("")
        self.__telephoneClient.setInputMask("00 00 00 00;_")
        self.__courielClient = QtWidgets.QLineEdit("")
        self.__nomChantier = QtWidgets.QLineEdit("")
        self.__nomClientLabel = QtWidgets.QLabel("Nom :")
        self.__prenomClientLabel = QtWidgets.QLabel("Prenom :")
        self.__adresseClientLabel = QtWidgets.QLabel("Adresse :")
        self.__cpClientLabel = QtWidgets.QLabel("Code postal :")
        self.__villeClientLabel = QtWidgets.QLabel("Ville :")
        self.__telephoneClientLabel = QtWidgets.QLabel("Telephone :")
        self.__courielClientLabel = QtWidgets.QLabel("Courriel :")
        self.__nomChantiertLabel = QtWidgets.QLabel("Nom du chantier :")
        self.__ouvrir = QtWidgets.QPushButton("Ouvrir")
        self.__ouvrir.setIcon(QtGui.QIcon("document-open.pgn"))
        self.__enregistrer = QtWidgets.QPushButton("Enregistrer")
        self.__enregistrer.setIcon(QtGui.QIcon("document-save.png"))
        self.__exporter = QtWidgets.QPushButton("Exporter")
        self.__exporter.setIcon(QtGui.QIcon("document-export.png"))
        self.__monter = QtWidgets.QPushButton("Monter")
        self.__monter.setIcon(QtGui.QIcon("go-up.png"))
        self.__descendre = QtWidgets.QPushButton("Descendre")
        self.__descendre.setIcon(QtGui.QIcon("go-down.png"))
        self.__supprimerLigne = QtWidgets.QPushButton("Supprimer")
        self.__supprimerLigne.setIcon(QtGui.Icon("edit-delete.png"))
        self.__tableChiffrage = QtWidgets.QTableWidget(0,6)
        enTeteTable =("Prestation","PrixUnitaire","Quantité","Total HT","TVA", "Total TTC")
        self.__tableChiffrage.setHorizontalHearderLabels(enTeteTable)
        self.__totauxEstimationLabel = QtWidgets.QLabel("HT : 0,00FrCFA\nTVA : 0,00FrCFA\nTTC : 0,00FrCFA")
        self.__chiffrageLayout = QtWidgets.QVBoxLayout()
        self.__clientFormLigne1 = QtWidgets.QHBoxLayout()
        self.__clientFormLigne1.addWidget(self.__nomClientLabel)
        self.__clientFormLigne1.addWidget(self.__nomClient)
        self.__clientFormLigne1.addWidget(self.__prenomClientLabel)
        self.__clientFormLigne1.addWidget(self.__prenomClient)
        self.__chiffrageLayout.addWidget(self.__clientFormLigne1)
        self.__clientFormLigne2 = QtWidgets.QHBoxLayout()
        self.__clientFormLigne2.addWidget(self.__adresseClientLabel)
        self.__clientFormLigne2.addWidget(self.__adresseClient)
        self.__chiffrageLayout.addWiget(self.__clientFormligne2)
        self.__clientFormLigne3 = Qtwidgets.QHBoxLayout()
        self.__clientFormligne3.addWidget(self.__cpClientLabel)
        self.__clientFormligne3.addWidget(self.__cpClient)
        self.__clientFormligne3.addWidget(self.__villeClientLabel)
        self.__clientFormligne3.addWidget(self.__villeClient)
        self.__chiffrageLayout.addLayout(self.__clientFormLigne3)
        self.__clientFormLigne4 = QtWidgets.QHBoxLayout()
        self.__clientFormLigne4.addWidget(self.__clientTelephoneLabel)
        self.__clientFormLigne4.addWidget(self.__clientTelephone)
        self.__clientFormLigne4.addWidget(self.__courrielClientLabel)
        self.__clientFormLigne4.addWidget(self.__courrielClient)
        self.__chiffrageLayout.addWidget(self.__clientFormLigne4)
        self.__clientFormLigne5 = QtWidgets.QHBoxLayout()
        self.__clientFormLigne5.addWidget(self.__nomChantierLabel)
        self.__clientFormLigne5.addWidget(self.__nomChantier)
        self.__chiffrageLayout.addLayout(self.__clientFormLigne5)
        self.__boutonsLayout = QtWidgets.QHBoxLayout()
        self.__boutonsLayout.addWidget(self.__ouvrir)
        self.__boutonsLayout.addWidget(self.__enregistrer)
        self.__boutonsLayout.addWidget(self.__exporter)
        self.__boutonsLayout.addWidget(self.__monter)
        self.__boutonsLayout.addWidget(self.__descendre)
        self.__boutonsLayout.addWidget(self.__supprimerLigne)
        self.__chiffrageLayout.addLayout(self.__boutonsLayout)
        self.__chiffrageLayout.addLayout(self.__tableChiffrage)
        self.__chiffrageLayout.addLayout(self.__totauxEstimationLabel)
        self.__prestationLayoutWidget = QtWidgets.QtWidget()
        self.__prestationLayoutWidget.setLayout(self.__prestationLayout)
        self.__chiffrageLayoutWidget = QtWidgets.QtWidget()
        self.__chiffrageLayoutWidget.setLayout(self.__chiffrageLayout)
        self.__centralWidget = QtWidgets.QSplitter()
        self.__centralWidget.addWidget(self.__prestationLayoutWidget)
        self.__centralWidget.addWidget(self.__chiffrageLayoutWidget)
        self.setCentralWidget(self.__centralWidget)
        self.peuplerCategories()
        self.peuplerPretations()
        self.__listeCategories.currenIndexChanged.connect(self.peulerPrestations)
        self.__barreRecherche.textChanged.connect(self.peuplerPrestations)
        self.__listePrestaQtWidgets.QDialog.__init__(self, parent)
	    self.setWindowTitle("Tarification")
        self.setWindowIcon(QtGui.QIcon())
        self.__listeCategories = QtWidgets.QComboBox()
        self.__idChiffrage = None
        self.__prestations = []
        self.__lignesChiffrage = []
        self.__listePrestations = Qtwidgets.QListWidget()
        self.__barreRecherche = QtWidgets.QLineEdit("")
        self.__creerPrestation = QtWidgets.QPushButton("Creer une prestation")
        self.__creerPrestation.setIcon(QGui.QIcon("edit-add.png"))
        self.__modifierPrestation = QtWidgets.QPushButton("Modifier une prestation")
        self.__modifierPrestation.setIcon(QGui.QIcon("stock-edit.png"))
        self.__supprimerPrestation = QtWidgets.QPushButton("Supprimer une prestation")
        self.__supprimerPrestation.setIcon(QGui.QIcon("stock_delete.png"))
        self.__prixUnitaire = 0.0
        self.__unite = " "
        self.__prixHT = 0.0
        self.__prixTVA = 0.0
        self.__prixTTC = 0.0
        self.__PrixUnitaireLabel = QtWidgets.QLabel("Prix unitaire: 0,00FrCFA")
        self.__quantite = QtWidgets.QDoubleSpinBox()
        self.__tvaLabel = QtWidgets.QLabel("TVA : ")
        self.__tva = QtWidgets.QDoubleSpinbox()
        self.__tva.setSuffix("%")
        self.__totauxLabel = QtWidgets.QLabel("HT : 0,00FrCFA\nTVA : 0,00FrCFA\nTTC : 0,00FrCFA")
        self.__ajouterPrestation = QtWidgets.QPushButton("Ajouter une prestation")
        self.__ajouterPrestation.setIcon(QtGui.QIcon("dialog-apply.png"))
        self.__prestationLayout = Qtwidgets.QVBoxLayout()
        self.__listeCategoriesLayout = QtWidgets.QFormLayout()
        self.__listeCategoriesLayout.addRow("Categorie :", self.__listecategories)
        self.__prestationLayout.addLayout(self.__listeCategorieLayout)
        self.__actionPrestationLayout = QtWidgets.QHBoxLayout()
        self.__actionPrestationLayout.addWidget(self.__creerPrestation)
        self.__actionPrestationLayout.addWidget(self.__modifierPrestation)
        self.__actionPrestationLayout.addWidget(self.__modifierPrestation)
        self.__actionPrestationLayout.addWidget(self.__supprimerPrestation)
        self.__actionPrestationLayout.addWidget(self.__actionPrestationLayout)
        self.__barreRechercheLayout = QtWidgets.QFormLayout()
        self.__barreRechercheLayout.addRow("Recherche : ", self.__barreRecherche)
        self.__prestationLayout.addLayout(self.__barreRechercheLayout)
        self.__prestationLayout.addWidget(self.__listePrestations)
        self.__quantiteTVALayout = QtWidgets.QHBoxLayout()
        self.__quantiteTVALayout.addWidget(self.__prixUnitaireLabel)
        self.__quantiteTVALayout.addStretch()
        self.__quantiteTVALayout.addWidget(self.__quantiteLabel)
        self.__quantiteTVALayout.addWidget(self.__quantite)
        self.__quantiteTVALayout.addStretch()
        self.__quantiteTVALayout.addWidget(self.__tvaLabel)
        self.__quantiteTVALayout.addWidget(self.__tva)
        self.__quantiteTVALayout.addWidget(self.__quantiteTVALayout)
        self.__quantiteTVALayout.addWidget(self.__totauxLabel)
        self.__quantiteTVALayout.addWidget(self.__ajouterPrestation)
        self.__nomClient = QtWidgets.QLineEdit("")
        self.__prenomClient = QtWidgets.QLineEdit("")
        self.__adresseClient = QtWidgets.QLineEdit("")
        self.__cpClient = QtWidgets.QLineEdit("")
        self.__cpClient.setInputMask("0000;_")
        self.__villeClient = QtWidgets.QLineEdit("")
        self.__telephoneClient = QtWidgets.QLineEdit("")
        self.__telephoneClient.setInputMask("00 00 00 00;_")
        self.__courielClient = QtWidgets.QLineEdit("")
        self.__nomChantier = QtWidgets.QLineEdit("")
        self.__nomClientLabel = QtWidgets.QLabel("Nom :")
        self.__prenomClientLabel = QtWidgets.QLabel("Prenom :")
        self.__adresseClientLabel = QtWidgets.QLabel("Adresse :")
        self.__cpClientLabel = QtWidgets.QLabel("Code postal :")
        self.__villeClientLabel = QtWidgets.QLabel("Ville :")
        self.__telephoneClientLabel = QtWidgets.QLabel("Telephone :")
        self.__courielClientLabel = QtWidgets.QLabel("Courriel :")
        self.__nomChantiertLabel = QtWidgets.QLabel("Nom du chantier :")
        self.__ouvrir = QtWidgets.QPushButton("Ouvrir")
        self.__ouvrir.setIcon(QtGui.QIcon("document-open.pgn"))
        self.__enregistrer = QtWidgets.QPushButton("Enregistrer")
        self.__enregistrer.setIcon(QtGui.QIcon("document-save.png"))
        self.__exporter = QtWidgets.QPushButton("Exporter")
        self.__exporter.setIcon(QtGui.QIcon("document-export.png"))
        self.__monter = QtWidgets.QPushButton("Monter")
        self.__monter.setIcon(QtGui.QIcon("go-up.png"))
        self.__descendre = QtWidgets.QPushButton("Descendre")
        self.__descendre.setIcon(QtGui.QIcon("go-down.png"))
        self.__supprimerLigne = QtWidgets.QPushButton("Supprimer")
        self.__supprimerLigne.setIcon(QtGui.Icon("edit-delete.png"))
        self.__tableChiffrage = QtWidgets.QTableWidget(0,6)
        enTeteTable =("Prestation","PrixUnitaire","Quantité","Total HT","TVA", "Total TTC")
        self.__tableChiffrage.setHorizontalHearderLabels(enTeteTable)
        self.__totauxEstimationLabel = QtWidgets.QLabel("HT : 0,00FrCFA\nTVA : 0,00FrCFA\nTTC : 0,00FrCFA")
        self.__chiffrageLayout = QtWidgets.QVBoxLayout()
        self.__clientFormLigne1 = QtWidgets.QHBoxLayout()
        self.__clientFormLigne1.addWidget(self.__nomClientLabel)
        self.__clientFormLigne1.addWidget(self.__nomClient)
        self.__clientFormLigne1.addWidget(self.__prenomClientLabel)
        self.__clientFormLigne1.addWidget(self.__prenomClient)
        self.__chiffrageLayout.addWidget(self.__clientFormLigne1)
        self.__clientFormLigne2 = QtWidgets.QHBoxLayout()
        self.__clientFormLigne2.addWidget(self.__adresseClientLabel)
        self.__clientFormLigne2.addWidget(self.__adresseClient)
        self.__chiffrageLayout.addWiget(self.__clientFormligne2)
        self.__clientFormLigne3 = Qtwidgets.QHBoxLayout()
        self.__clientFormligne3.addWidget(self.__cpClientLabel)
        self.__clientFormligne3.addWidget(self.__cpClient)
        self.__clientFormligne3.addWidget(self.__villeClientLabel)
        self.__clientFormligne3.addWidget(self.__villeClient)
        self.__chiffrageLayout.addLayout(self.__clientFormLigne3)
        self.__clientFormLigne4 = QtWidgets.QHBoxLayout()
        self.__clientFormLigne4.addWidget(self.__clientTelephoneLabel)
        self.__clientFormLigne4.addWidget(self.__clientTelephone)
        self.__clientFormLigne4.addWidget(self.__courrielClientLabel)
        self.__clientFormLigne4.addWidget(self.__courrielClient)
        self.__chiffrageLayout.addWidget(self.__clientFormLigne4)
        self.__clientFormLigne5 = QtWidgets.QHBoxLayout()
        self.__clientFormLigne5.addWidget(self.__nomChantierLabel)
        self.__clientFormLigne5.addWidget(self.__nomChantier)
        self.__chiffrageLayout.addLayout(self.__clientFormLigne5)
        self.__boutonsLayout = QtWidgets.QHBoxLayout()
        self.__boutonsLayout.addWidget(self.__ouvrir)
        self.__boutonsLayout.addWidget(self.__enregistrer)
        self.__boutonsLayout.addWidget(self.__exporter)
        self.__boutonsLayout.addWidget(self.__monter)
        self.__boutonsLayout.addWidget(self.__descendre)
        self.__boutonsLayout.addWidget(self.__supprimerLigne)
        self.__chiffrageLayout.addLayout(self.__boutonsLayout)
        self.__chiffrageLayout.addLayout(self.__tableChiffrage)
        self.__chiffrageLayout.addLayout(self.__totauxEstimationLabel)
        self.__prestationLayoutWidget = QtWidgets.QtWidget()
        self.__prestationLayoutWidget.setLayout(self.__prestationLayout)
        self.__chiffrageLayoutWidget = QtWidgets.QtWidget()
        self.__chiffrageLayoutWidget.setLayout(self.__chiffrageLayout)
        self.__centralWidget = QtWidgets.QSplitter()
        self.__centralWidget.addWidget(self.__prestationLayoutWidget)
        self.__centralWidget.addWidget(self.__chiffrageLayoutWidget)
        self.setCentralWidget(self.__centralWidget)
        self.peuplerCategories()
        self.peuplerPretations()
        self.__listeCategories.currenIndexChanged.connect(self.peulerPrestations)
        self.__barreRecherche.textChanged.connect(self.peuplerPrestations)
        self.__listePrestations.itemClicked.connect(self.ouvrirFiche)
        self.__quantite.valueChanged.connect(self.calculerTotaux)
        self.__tva.valueChanged.connect(self.calculerTotaux)
        self.__ajouterPrestation.clicked.connect(self.ajouterLigneChiffrage)
        self.__monter.clicked.connect(self.monteLigne)
        self.__descendre.clicked.connect(self.descendreLigne)
        self.__supprimerLigne.clicked.connect(self.supprimerLigne)
        self.__creerPrestation.clicked.connect(self.nouvellePrestation)
        self.__modifierPrestation.clicked.connect(self.modifierPrestation)
        self.__supprimerPrestation.clicked.connect(self.supprimerPrestation)
        self.__enregistrerPrestation.clicked.connect(self.enregistrerPrestation)
        self.show()
app = QtWidgets.QApplication(sys.argv)
fenetre = Tarification() 
app.exec_()
baseDeDonnees.close()
        tions.itemClicked.connect(self.ouvrirFiche)
        self.__quantite.valueChanged.connect(self.calculerTotaux)
        self.__tva.valueChanged.connect(self.calculerTotaux)
        self.__ajouterPrestation.clicked.connect(self.ajouterLigneChiffrage)
        self.__monter.clicked.connect(self.monteLigne)
        self.__descendre.clicked.connect(self.descendreLigne)
        self.__supprimerLigne.clicked.connect(self.supprimerLigne)
        self.__creerPrestation.clicked.connect(self.nouvellePrestation)
        self.__modifierPrestation.clicked.connect(self.modifierPrestation)
        self.__supprimerPrestation.clicked.connect(self.supprimerPrestation)
        self.__enregistrerPrestation.clicked.connect(self.enregistrerPrestation)
        self.show()
app = QtWidgets.QApplication(sys.argv)
fenetre = Tarification() 
app.exec_()
baseDeDonnees.close()
        