# Generated by Django 4.1.7 on 2023-03-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisateur ',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('NGSER', 'NGSER'), ('NOKIA', 'NOKIA'), ('GOPA', 'GOPA'), ('HUAWE', 'HUAWE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('CNI', 'CNI'), ('PASSPORT', 'PASSPORT'), ('PERMIS CONDUITE', 'PERMIS CONDUITE'), ('ATTESTATION', 'ATTESTATION')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=10)),
                ('numero_pieces', models.CharField(default=True, max_length=100)),
                ('lieu_naissance', models.CharField(default=True, max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.service')),
                ('type_pieces', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.typepieces')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('PH', 'HP'), ('DELL', 'DELL'), ('LENEVO', 'LENEVO'), ('ASUS', 'ASUS'), ('ACER', 'ACER'), ('MAC', 'MAC'), ('TSHIBA', 'TASHIBA')], max_length=10)),
                ('numero_serie', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=50)),
                ('processeur', models.CharField(max_length=10)),
                ('rame', models.PositiveIntegerField()),
                ('disque_dur', models.CharField(choices=[('128G', '128G'), ('250G', '250G'), ('320G', '320G'), ('500G', '500G'), ('750G', '750G'), ('1TO', '1TO')], max_length=10)),
                ('type_disque_dur', models.CharField(choices=[('HDD', 'HDD'), ('SSD SATA', 'SSD SATA'), ('SSD M2', 'SSD M2')], max_length=10)),
                ('taille_ecran', models.CharField(choices=[('10 Pouce', '10 Pouce'), ('13 Pouce', '13 Pouce'), ('14 Pouce', '14 Pouce'), ('15 Pouce', '15 Pouce'), ('17 Pouce', '17 Pouce')], max_length=50)),
                ('etat_achat', models.CharField(choices=[('NEUF', 'NEUF'), ('OCCASION', 'OCCASION')], max_length=20)),
                ('garantie', models.CharField(max_length=10)),
                ('date_acquisition', models.DateField()),
                ('type_materiel', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.typemateriel')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('materiel', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_part', models.DateField(blank=True, help_text='Date de part', null=True)),
                ('date_retour', models.DateField(blank=True, help_text='Date de retour', null=True)),
                ('status', models.CharField(choices=[('EN MAINTENANCE', 'En maintenance'), ('EN STOCK', 'En stock')], default=True, max_length=50)),
                ('maintenancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.maintenancier')),
                ('materiels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name="Debut d'attribution")),
                ('status', models.CharField(max_length=50)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.materiel')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.ressource')),
            ],
        ),
    ]
