# Generated by Django 4.1.7 on 2023-03-08 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0002_alter_maintenancier_materiel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='date_naissances',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
