# Generated by Django 4.1.7 on 2023-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0004_alter_attribution_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribution',
            old_name='materiel',
            new_name='mumero_de_serie',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='status',
        ),
        migrations.AlterField(
            model_name='attribution',
            name='date_debut',
            field=models.DateField(auto_now_add=True, verbose_name="Debut d'attribution"),
        ),
    ]
