# Generated by Django 4.1.7 on 2023-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0005_rename_materiel_attribution_mumero_de_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
