# Generated by Django 4.1.7 on 2023-03-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0006_ressource_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='slug',
        ),
        migrations.AddField(
            model_name='ressource',
            name='fonction',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
