# Generated by Django 4.1.7 on 2023-03-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0007_remove_ressource_slug_ressource_fonction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='fichier',
            field=models.FileField(default=True, upload_to='uploads/'),
        ),
    ]
