# Generated by Django 4.1.7 on 2023-03-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0009_remove_fournisseur_materiel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='fichier',
        ),
    ]
