# Generated by Django 4.1.7 on 2023-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0012_remove_attribution_fichier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utlisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(choices=[('Admin', 'ADMIN'), ('IT', 'IT'), ('Superviseur', 'SUPERVISEUR')], default=False),
        ),
    ]
