# Generated by Django 4.1.7 on 2023-03-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0013_alter_user_options_alter_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('IT', 'IT'), ('Superviseur', 'SUPERVISEUR')], default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
