# Generated by Django 4.1.7 on 2023-03-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0014_user_profile_alter_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
