# Generated by Django 4.1.7 on 2023-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0015_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('IT', 'IT'), ('SUPERVISEUR', 'SUPERVISEUR')], default=True, max_length=50),
        ),
    ]
