# Generated by Django 4.1.7 on 2023-03-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0016_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='date_acquisition',
            field=models.DateField(auto_now_add=True),
        ),
    ]
