# Generated by Django 4.1.7 on 2023-03-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0019_alter_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='materiel',
            name='garantie',
            field=models.PositiveIntegerField(help_text='CE CHAMP EST EN MOIS'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('IT', 'IT'), ('SUPERVISEUR', 'SUPERVISEUR')], default=True, max_length=50),
        ),
    ]
