# Generated by Django 4.1.7 on 2023-03-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0020_rename_admin_user_status_alter_materiel_garantie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancier',
            name='materiel',
        ),
    ]
