# Generated by Django 4.1.7 on 2023-03-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0021_remove_maintenancier_materiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=150)),
                ('date_restitution', models.DateField(auto_now_add=True)),
                ('fichier', models.FileField(max_length=254, upload_to='upload')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.ressource')),
            ],
        ),
    ]
