# Generated by Django 4.1.7 on 2023-03-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0022_restitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='restitution',
            name='materiel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.materiel'),
        ),
    ]
