# Generated by Django 4.1.7 on 2023-03-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0023_restitution_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='mumero_de_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.materiel', unique=True),
        ),
    ]
