# Generated by Django 4.1.7 on 2023-03-31 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0024_alter_attribution_mumero_de_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='mumero_de_serie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parcinformatique.materiel'),
        ),
    ]
