# Generated by Django 4.1.7 on 2023-03-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0025_alter_attribution_mumero_de_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcinformatique.service'),
        ),
    ]
