# Generated by Django 4.1.7 on 2023-04-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0026_alter_ressource_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur'},
        ),
    ]
