# Generated by Django 4.1.7 on 2023-04-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0027_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('IT', 'IT'), ('SUPERVISEUR', 'SUPERVISEUR')], default=True, max_length=50),
        ),
    ]
