# Generated by Django 4.1.7 on 2023-04-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parcinformatique', '0028_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='content_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='mumero_de_serie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='parcinformatique.materiel'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcinformatique.ressource'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenancier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcinformatique.maintenancier'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='materiels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcinformatique.materiel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='marque',
            field=models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('LENEVO', 'LENEVO'), ('ASUS', 'ASUS'), ('ACER', 'ACER'), ('MAC', 'MAC'), ('TSHIBA', 'TASHIBA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='type_materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcinformatique.typemateriel'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='type_pieces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcinformatique.typepieces'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='materiel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiel', to='parcinformatique.materiel'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressource', to='parcinformatique.ressource'),
        ),
    ]
