# Generated by Django 4.1.7 on 2023-04-11 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0030_remove_attribution_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restitution',
            name='materiel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiel', to='parcinformatique.attribution'),
        ),
    ]
