# Generated by Django 4.1.7 on 2023-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0031_alter_restitution_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restitution',
            name='materiel',
        ),
        migrations.AddField(
            model_name='restitution',
            name='materiel',
            field=models.ManyToManyField(default=True, related_name='materiel', to='parcinformatique.attribution'),
        ),
    ]
