# Generated by Django 4.1.7 on 2023-04-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0032_remove_restitution_materiel_restitution_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restitution',
            name='materiel',
        ),
        migrations.AddField(
            model_name='restitution',
            name='materiel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiel', to='parcinformatique.attribution'),
        ),
    ]
