# Generated by Django 4.1.7 on 2023-04-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0035_alter_restitution_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restitution',
            name='fichier',
            field=models.FileField(max_length=150, upload_to='upload'),
        ),
    ]
