# Generated by Django 4.1.7 on 2023-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcinformatique', '0036_alter_restitution_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='status',
            field=models.BooleanField(choices=[(False, 'no'), (True, 'yes')], default=False),
        ),
    ]
